/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/Splitties/refreshVersions
 */
public object Libs {
    
    public const val credentials: String = "androidx.credentials:credentials:_"

    public const val credentials_play_services_auth: String =
        "androidx.credentials:credentials-play-services-auth:_"

    public const val datastore: String = "androidx.datastore:datastore:_"

    public const val exifinterface: String = "androidx.exifinterface:exifinterface:_"


    public const val googleid: String = "com.google.android.libraries.identity.googleid:googleid:_"

    public const val secrets_gradle_plugin: String =
        "com.google.android.libraries.mapsplatform.secrets-gradle-plugin:secrets-gradle-plugin:_"

    public const val places: String = "com.google.android.libraries.places:places:_"


    public const val maps_compose_utils: String = "com.google.maps.android:maps-compose-utils:_"

    public const val android_image_cropper: String = "com.vanniktech:android-image-cropper:_"


    public const val imageCompressor: String = "id.zelory:compressor:_"


    public const val resaca: String = "io.github.sebaslogen:resaca:_"

    public const val resacahilt: String = "io.github.sebaslogen:resacahilt:_"

    public const val koin_core: String = "io.insert-koin:koin-core:_"

}
